# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Lucky_config = debug
  App_config = debug

else ifeq ($(config),release)
  Lucky_config = release
  App_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Lucky App

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Lucky:
ifneq (,$(Lucky_config))
	@echo "==== Building Lucky ($(Lucky_config)) ===="
	@${MAKE} --no-print-directory -C Lucky -f Makefile.wasm.mk config=$(Lucky_config)
endif

App: Lucky
ifneq (,$(App_config))
	@echo "==== Building App ($(App_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile.wasm.mk config=$(App_config)
endif

clean:
	@${MAKE} --no-print-directory -C Lucky -f Makefile.wasm.mk clean
	@${MAKE} --no-print-directory -C App -f Makefile.wasm.mk clean

help:
	@echo "Usage: make -f Makefile.wasm.mk [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  wasm"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Lucky"
	@echo "   App"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"