# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifeq ($(config),debug)
  ImGui_config = Debug
  ImGuizmo_config = Debug
  Yaml_config = Debug
  Lucky_config = Debug
  LuckyEditor_config = Debug
  SandBox_config = Debug

else ifeq ($(config),release)
  ImGui_config = Release
  ImGuizmo_config = Release
  Yaml_config = Release
  Lucky_config = Release
  LuckyEditor_config = Release
  SandBox_config = Release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Lucky LuckyEditor SandBox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Vendors/ImGui -f Makefile.emscripten.mk CONFIG=$(ImGui_config)
endif

ImGuizmo:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGuizmo ($(ImGuizmo_config)) ===="
	@${MAKE} --no-print-directory -C Vendors/ImGuizmo -f Makefile.emscripten.mk CONFIG=$(ImGuizmo_config)
endif

Yaml: ImGui ImGuizmo
ifneq (,$(Yaml_config))
	@echo "==== Building Yaml ($(Yaml_config)) ===="
	@${MAKE} --no-print-directory -C Vendors/yaml-cpp -f Makefile.emscripten.mk CONFIG=$(Yaml_config)
endif

Lucky: ImGui ImGuizmo Yaml
ifneq (,$(Lucky_config))
	@echo "==== Building Lucky ($(Lucky_config)) ===="
	@${MAKE} --no-print-directory -C Lucky -f Makefile.emscripten.mk CONFIG=$(Lucky_config)
endif

LuckyEditor: Lucky
ifneq (,$(LuckyEditor_config))
	@echo "==== Building Lucky Editor ($(LuckyEditor_config)) ===="
	@${MAKE} --no-print-directory -C LuckyEditor -f Makefile.emscripten.mk CONFIG=$(LuckyEditor_config)
endif

SandBox: Lucky
ifneq (,$(SandBox_config))
	@echo "==== Building SandBox ($(SandBox_config)) ===="
	@${MAKE} --no-print-directory -C SandBox -f Makefile.emscripten.mk CONFIG=$(SandBox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Lucky -f Makefile.emscripten.mk clean
	@${MAKE} --no-print-directory -C SandBox -f Makefile.emscripten.mk clean

help:
	@echo "Usage: make -f Makefile.emscripten.mk [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  wasm"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Lucky"
	@echo "   App"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"