from sys import argv
import os
import re

requestedCSFile = str(argv[1])
projectName = None
if len(argv) > 2:
	projectName = str(argv[2])
requestedClassName = os.path.splitext(os.path.basename(requestedCSFile))[0]

f = open(requestedCSFile, "r")
oldBuffer = str(f.read())
f.close()

regex = f"class {requestedClassName}.*static {requestedClassName}"
pattern = re.compile(regex, re.DOTALL)
newBuffer = re.sub(pattern, "class " + requestedClassName + " {\nstatic " + requestedClassName, oldBuffer) # remove SWIG autogenerated code between

if projectName != None:
	regex = f"DllImport\\(\"{projectName}"
	pattern = re.compile(regex, re.DOTALL)
	newBuffer = re.sub(pattern, f"DllImport(\"__Internal", newBuffer) 

if newBuffer != oldBuffer:
  f = open(requestedCSFile, "w")
  f.write(newBuffer)
  f.close()
